import { NextRequest, NextResponse } from 'next/server'
import { sql } from '@/lib/db'
// Note: Install bcryptjs: npm install bcryptjs @types/bcryptjs
// For now using simple storage - should hash passwords in production

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { name, email, password } = body

    if (!name || !email || !password) {
      return NextResponse.json(
        { error: 'Name, email, and password are required' },
        { status: 400 }
      )
    }

    if (password.length < 6) {
      return NextResponse.json(
        { error: 'Password must be at least 6 characters' },
        { status: 400 }
      )
    }

    // Check if user already exists
    const existing = await sql`
      SELECT id FROM users WHERE email = ${email}
    `

    if (existing.length > 0) {
      return NextResponse.json(
        { error: 'Email already registered' },
        { status: 400 }
      )
    }

    // Hash password (TODO: Use bcryptjs in production)
    // For now, storing plain text - NOT SECURE for production!
    const hashedPassword = password // TODO: await bcrypt.hash(password, 10)

    // Create user (UUID will be generated by database)
    // Note: If password_hash column doesn't exist, run: ALTER TABLE users ADD COLUMN password_hash TEXT;
    let result
    try {
      result = await sql`
        INSERT INTO users (email, name, password_hash)
        VALUES (${email}, ${name}, ${hashedPassword})
        RETURNING id, email, name, created_at
      `
    } catch (dbError: any) {
      // If column doesn't exist, try without password_hash (for backward compatibility)
      if (dbError.message?.includes('password_hash') || dbError.message?.includes('column')) {
        console.error('password_hash column missing. Run migration: ALTER TABLE users ADD COLUMN password_hash TEXT;')
        result = await sql`
          INSERT INTO users (email, name)
          VALUES (${email}, ${name})
          RETURNING id, email, name, created_at
        `
      } else {
        throw dbError
      }
    }

    // Ensure ID is returned as string
    const userId = typeof result[0].id === 'string' ? result[0].id : result[0].id.toString()

    // Generate simple token (in production, use JWT)
    const token = Buffer.from(`${userId}:${Date.now()}`).toString('base64')

    return NextResponse.json({
      user: {
        id: userId,
        email: result[0].email,
        name: result[0].name,
      },
      token,
    })
  } catch (error) {
    console.error('Error in POST /api/auth/signup:', error)
    return NextResponse.json(
      { error: 'Failed to create account' },
      { status: 500 }
    )
  }
}

